version: '3.9'
services:
  golang-api-template:
    container_name: golang-api-template
    build: .
    ports:
      - '8080:8080' # change port here
    volumes:
      - ./logs/:/app/logs/
      - ./app.env:/app/app.env
