# Use postgres/example user/password credentials
version: '3.9'

services:

  postgres_db:
    image: postgres:16.2
    container_name: postgres_db
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: khiemle
      POSTGRES_PASSWORD: khiemle2409
    ports:
      - 5432:5432

    networks:
      golang-api-template-network:
        aliases:
          - postgres_db


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - golang-api-template-network


networks:
  golang-api-template-network:
    external: true
